# Generated by Django 3.2.9 on 2021-11-11 21:25

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pica.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Company Code')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Name')),
            ],
        ),
        migrations.CreateModel(
            name='DivDept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nama Divisi/Departemen')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_forum', models.CharField(blank=True, max_length=100, null=True, validators=[pica.validators.validate_empty])),
                ('keterangan', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('notulen', models.CharField(blank=True, max_length=50, null=True, verbose_name='Notulen Meeting')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('meeting2forum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum2meeting', to='pica.forum', verbose_name='Meeting Forum')),
            ],
        ),
        migrations.CreateModel(
            name='Peserta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nama Peserta')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email address')),
                ('bod', models.BooleanField(default=False, verbose_name='Apakah masuk dalam list BOD?')),
            ],
        ),
        migrations.CreateModel(
            name='Topik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_topik', models.CharField(blank=True, max_length=100, null=True, verbose_name='Topik')),
                ('problem', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Problem/Information')),
                ('action', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Action')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField(null=True, verbose_name='Due date')),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('HOLD', 'HOLD'), ('PROGRESS', 'PROGRESS'), ('CLOSE', 'CLOSE')], default='OPEN', max_length=8)),
                ('expired', models.BooleanField(default=False)),
                ('topik2company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company2topik', to='pica.company', verbose_name='Problem Owner')),
                ('topik2divdept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='divdept2topik', to='pica.divdept', verbose_name='Function/Divisi/Departemen')),
                ('topik2meeting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting2topik', to='pica.meeting', verbose_name='Meeting')),
                ('topik2user', models.ManyToManyField(related_name='user2topik', to=settings.AUTH_USER_MODEL, verbose_name='Person in charge')),
            ],
        ),
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nama Peserta')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email address')),
                ('in_charge', models.BooleanField(default=False, verbose_name='In Charge')),
                ('pic2topik', models.ManyToManyField(related_name='topik2pic', to='pica.Topik', verbose_name='Topik')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting2peserta',
            field=models.ManyToManyField(related_name='peserta2meeting', to='pica.Peserta', verbose_name='Peserta meeting'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_activity', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Activity')),
                ('keterangan', models.CharField(max_length=255, verbose_name='Activity/Action')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date (New)')),
                ('expired', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('HOLD', 'HOLD'), ('PROGRESS', 'PROGRESS'), ('CLOSE', 'CLOSE')], default='OPEN', max_length=8)),
                ('activity2topik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topik2activity', to='pica.topik')),
                ('activity2user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2activity', to=settings.AUTH_USER_MODEL, verbose_name='PIC')),
            ],
        ),
    ]
