# Generated by Django 3.2.9 on 2021-11-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topik',
            name='topik2peserta',
            field=models.ManyToManyField(related_name='peserta2topik', to='pica.Peserta', verbose_name='Known By'),
        ),
    ]
