# Generated by Django 3.2.9 on 2021-11-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pica', '0002_topik_topik2peserta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('nama_bod', models.CharField(max_length=40)),
            ],
        ),
    ]
