# Generated by Django 3.2.9 on 2021-11-16 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pica', '0004_signature_signature2forum'),
    ]

    operations = [
        migrations.AddField(
            model_name='peserta',
            name='presdir',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
