# Generated by Django 3.2.9 on 2021-11-16 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pica', '0005_peserta_presdir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peserta',
            name='presdir',
        ),
        migrations.AddField(
            model_name='signature',
            name='presdir',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
