# Generated by Django 3.2.9 on 2021-11-20 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pica', '0007_auto_20211120_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='lines',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
