# Generated by Django 3.2.9 on 2021-11-20 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pica', '0008_signature_lines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='lines',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
