# Generated by Django 3.2.9 on 2021-11-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pica', '0011_auto_20211124_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topik',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSE', 'CLOSE')], default='OPEN', max_length=8),
        ),
    ]
