# Generated by Django 3.2.9 on 2021-12-01 01:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pica', '0012_alter_topik_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='expired',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='keterangan',
            field=models.CharField(max_length=255, null=True, verbose_name='Activity/Action'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSE', 'CLOSE')], default='OPEN', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting2peserta',
            field=models.ManyToManyField(null=True, related_name='peserta2meeting', to='pica.Peserta', verbose_name='Peserta meeting'),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='bod',
            field=models.BooleanField(default=False, null=True, verbose_name='Apakah masuk dalam list BOD?'),
        ),
        migrations.AlterField(
            model_name='pic',
            name='in_charge',
            field=models.BooleanField(default=False, null=True, verbose_name='In Charge'),
        ),
        migrations.AlterField(
            model_name='pic',
            name='pic2topik',
            field=models.ManyToManyField(null=True, related_name='topik2pic', to='pica.Topik', verbose_name='Topik'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='nama_bod',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='signature',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='topik',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='topik',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='topik',
            name='expired',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='topik',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSE', 'CLOSE')], default='OPEN', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='topik',
            name='topik2peserta',
            field=models.ManyToManyField(null=True, related_name='peserta2topik', to='pica.Peserta', verbose_name='Known By'),
        ),
        migrations.AlterField(
            model_name='topik',
            name='topik2user',
            field=models.ManyToManyField(null=True, related_name='user2topik', to=settings.AUTH_USER_MODEL, verbose_name='Person in charge'),
        ),
    ]
