# Generated by Django 3.2.9 on 2021-12-01 01:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pica', '0013_auto_20211201_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting2peserta',
            field=models.ManyToManyField(related_name='peserta2meeting', to='pica.Peserta', verbose_name='Peserta meeting'),
        ),
        migrations.AlterField(
            model_name='pic',
            name='pic2topik',
            field=models.ManyToManyField(related_name='topik2pic', to='pica.Topik', verbose_name='Topik'),
        ),
        migrations.AlterField(
            model_name='topik',
            name='topik2peserta',
            field=models.ManyToManyField(related_name='peserta2topik', to='pica.Peserta', verbose_name='Known By'),
        ),
        migrations.AlterField(
            model_name='topik',
            name='topik2user',
            field=models.ManyToManyField(related_name='user2topik', to=settings.AUTH_USER_MODEL, verbose_name='Person in charge'),
        ),
    ]
